service: serverless-hello-world

provider:
  name: aws
  runtime: nodejs10.x

  functions:
    helloWorld:
      handler: index.handler
      events:
        - http:
          path: haihai
          method: get
          cors: true
