AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Oh Hai there service
Resources:
  GreetingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GreetingsFunction
      Runtime: nodejs10.x
      Handler: index.handler
      CodeUri: app/
      Events:
        OhHaiApi:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
